### PR TITLE
Fix the failing PHP 5.4 builds on travisci

### PR DESCRIPTION
**Pull request by kdambekalns**
Feel free to squash the commits into one. :)

### CODE REVIEW

**Comment by kdambekalns** [comment]
Bleh, obviously the "mime" should read "mtime" in the message for 3631f94

**Comment by kdambekalns** [comment]
For completeness, here's the result for those changes: http://travis-ci.org/#!/kdambekalns/Scisr/builds/586779

**Comment by iangreenleaf** [comment]
Thanks! :star:

**Comment by iangreenleaf** [comment]
I got a failure on travis after merging this, so I committed an extra bit of fix. In the course of troubleshooting I realized that these tests weren't properly connecting to the test DB and fixed that too. So hopefully between those two additions, the test will be stable now.

**Pull request merged**
